name: cds
version: 0.1.0
appVersion: 0.35.1
description: Enterprise-Grade Continuous Delivery & DevOps Automation Open Source Platform.
keywords:
- cds
- devops
- scale
- stateless
- high-availability
home: https://github.com/ovh/cds
icon: https://raw.githubusercontent.com/ovh/cds/master/logo-background.png
sources:
- https://github.com/ovh/cds
maintainers:
- name: joel seguillon
  email: joel.sxxxxxon@gmail.com
engine: gotpl
