apiVersion: v1
kind: Service
metadata:
  name: {{ template "cds.fullname" . }}-gui
  labels:
    app: {{ template "cds.fullname" . }}-gui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: 80
    targetPort:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ template "cds.fullname" . }}-api
