apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cds.fullname" . }}
  labels:
    app: {{ template "cds.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.cdslPassword }}
  cds-password: {{ default "" .Values.cdsPassword | b64enc | quote }}
  {{ else }}
  cds-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
